--
-- PostgreSQL database dump
--

-- Dumped from database version 14.15 (Homebrew)
-- Dumped by pg_dump version 14.15 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: contato; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contato (
    id_contato bigint NOT NULL,
    idade_contato integer,
    nome_contato character varying(200) NOT NULL
);


--
-- Name: contato_id_contato_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contato ALTER COLUMN id_contato ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contato_id_contato_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: telefone; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.telefone (
    id_telefone bigint NOT NULL,
    numero_telefone character varying(20) NOT NULL,
    id_contato bigint NOT NULL
);


--
-- Name: telefone_id_telefone_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.telefone ALTER COLUMN id_telefone ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.telefone_id_telefone_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: contato; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.contato (id_contato, idade_contato, nome_contato) FROM stdin;
1	21	Felipe Guerrera
2	82	Paul Mccartney
3	40	John Lennon
5	58	George Harrison
6	85	Ringo Starr
\.


--
-- Data for Name: telefone; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.telefone (id_telefone, numero_telefone, id_contato) FROM stdin;
1	16992303711	1
2	16998726316	2
3	16923749823	2
4	16927396781	3
6	16992879834	5
7	16997236853	6
\.


--
-- Name: contato_id_contato_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.contato_id_contato_seq', 6, true);


--
-- Name: telefone_id_telefone_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.telefone_id_telefone_seq', 7, true);


--
-- Name: contato contato_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contato
    ADD CONSTRAINT contato_pkey PRIMARY KEY (id_contato);


--
-- Name: telefone telefone_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telefone
    ADD CONSTRAINT telefone_pkey PRIMARY KEY (id_telefone);


--
-- Name: telefone fkq3t6bittts05mia6n1r6r9id9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telefone
    ADD CONSTRAINT fkq3t6bittts05mia6n1r6r9id9 FOREIGN KEY (id_contato) REFERENCES public.contato(id_contato);


--
-- PostgreSQL database dump complete
--

